# INSTALL PYTHON IMAGE
FROM python:3.6

# INSTALL TOOLS
RUN apt-get update \
    && apt-get -y install unzip \
    && apt-get -y install libaio-dev \
    && mkdir -p /opt/data/api

ADD ./oracle-instantclient/ /opt/data
ADD ./install-instantclient.sh /opt/data
ADD ./requirements.txt /opt/data

WORKDIR /opt/data

ENV ORACLE_HOME=/opt/oracle/instantclient
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME

ENV OCI_HOME=/opt/oracle/instantclient
ENV OCI_LIB_DIR=/opt/oracle/instantclient
ENV OCI_INCLUDE_DIR=/opt/oracle/instantclient/sdk/include


# INSTALL INSTANTCLIENT AND DEPENDENCIES
RUN chmod 777 ./install-instantclient.sh \
    && pip install --no-cache-dir -r requirements.txt

ADD . /opt/data

EXPOSE 5000

#I have my server.py code under api folder

CMD ["python3","./api/server.py"]
