version: '3'
services:
  python-app:
    build:
      context: ./docker/flask
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "5000:5000"
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "4201:80"

