# Stage 1
FROM node:12.16.1-alpine as build-step
WORKDIR /usr/src/app
COPY package.json package-lock.json ./

EXPOSE 80 443

RUN npm install
COPY . .
RUN npm run build --prod

# Stage 2
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build-step /usr/src/app/dist/bim-angulardashboard/ /usr/share/nginx/html

