version: '3'
services:
  python-app:
    build:
      context: ./docker/flask
      dockerfile: Dockerfile
      args:
        buildno: 1
    network_mode: "host"
    ports:
      - "5000:5000"
    volumes:
      - ./in000031-batch_dashboard/docker/flask/:/var/www/html # after : its the location in the container OS
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    network_mode: "host"
    ports:
      - "4201:80"
    volumes:
      - ./in000031-batch_dashboard/:/var/www/html # after : its the location in the container OS
